# Generated by Django 4.2.7 on 2023-11-14 19:34

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("budgets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="amount_budgeted_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("USD", "US Dollar")],
                default="USD",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="monthly_income_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("USD", "US Dollar")],
                default="USD",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("USD", "US Dollar")],
                default="USD",
                editable=False,
                max_length=3,
            ),
        ),
    ]
