# Generated by Django 4.2.7 on 2023-11-11 22:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("budgets", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="catagory",
            new_name="category",
        ),
    ]
